### ISSUE TITLE
Tests fail on armhf - log provided

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [canonical/snapd-glib#162]
Please see https://launchpadlibrarian.net/739560793/buildlog_ubuntu-oracular-armhf.snapd-glib_1.65-0ubuntu0~ubuntu24.10~ppa3_BUILDING.txt.gz

**Comment by rikmills** [comment]
For reference, we (Kubuntu/Lubuntu/UbuntuStudio) need to get the qt6 port v1.65 or greater into Ubuntu oracular before feature freeze. Needed for Qt6 plasma-discover software centre.

**Comment by robert-ancell** [comment]
@sergio-costas can you have a look at this? I suspect it was added in cc743d3d but I couldn't see anything obvious that would break on armhf.

**Comment by rikmills** [comment]
snapd-glib v1.65 is now in Ubuntu Oracular proposed, with build time tests skipped as we have the autopkgtest infra there. 

See: https://launchpad.net/ubuntu/+source/snapd-glib/1.65-0ubuntu1

As was predictable, we now see this test failure manifest itself in the autopkgtest results:

https://autopkgtest.ubuntu.com/packages/s/snapd-glib/oracular/armhf

Which results in the package being blocked from migration to the release pocket:

https://ubuntu-archive-team.ubuntu.com/proposed-migration/update_excuses.html#snapd-glib

So any help/solution would be great, as this is now a real blocker to getting dependant packages (plasma-discover etc) into oracular.

Thanks

**Comment by sergio-costas** [comment]
I returned today from holidays. I'll check this ASAP.

**Comment by ScarlettGatelyMoore** [comment]
Any luck on this? We had to disable snaps in Kubuntu software store Discover, which is not something I want.

**Comment by rikmills** [comment]
@robert-ancell @sergio-costas as above

**Comment by sergio-costas** [comment]
Sorry for the delay... I'll check it right now.

**Comment by sergio-costas** [comment]
Ok, I suspect that the problem is either in mock-snapd.c:

![imagen](https://github.com/user-attachments/assets/c65878f3-dc95-4bc2-b70c-b67b68c6cc01)

or in snapd-json.c:

![imagen](https://github.com/user-attachments/assets/923b7639-c19c-4650-904f-242b6c385547)

Maybe in armhf the type is neither G_TYPE_INT64 nor STRING, and it returns NULL?

**Comment by rikmills** [comment]
> @ScarlettGatelyMoore @rikmills Can you test #176 please?

I'll test this, as the Ubuntu upload was mine.

**Comment by sergio-costas** [comment]
Thanks.

**Comment by rikmills** [comment]
@sergio-costas The actual build instead of the tests is now failing on multiple architectures in oracular.

This appears not related to you patches and a build without the patches fails in the same way.

So as the build fails  before any tests are executed, I am unable to test PR

See: https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3997/+sourcepub/16436199/+listing-archive-extra

https://launchpadlibrarian.net/748339673/buildlog_ubuntu-oracular-i386.snapd-glib_1.65-0ubuntu2~ppa1_BUILDING.txt.gz

> FAILED: snapd-glib/Snapd-2.gir 
env PKG_CONFIG_PATH=/<<PKGBUILDDIR>>/obj-i686-linux-gnu/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/i686-linux-gnu-g-ir-scanner --quiet --no-libtool --namespace=Snapd --nsversion=2 --warn-all --output snapd-glib/Snapd-2.gir --c-include=snapd-glib/snapd-glib.h -DSNAPD_COMPILATION=1 -I/<<PKGBUILDDIR>>/snapd-glib -I/<<PKGBUILDDIR>>/obj-i686-linux-gnu/snapd-glib -I/<<PKGBUILDDIR>>/snapd-glib/.. -I/<<PKGBUILDDIR>>/obj-i686-linux-gnu/snapd-glib/.. --filelist=/<<PKGBUILDDIR>>/obj-i686-linux-gnu/snapd-glib/libsnapd-glib-2.so.1.0.0.p/Snapd_2_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --pkg-export=snapd-glib --cflags-begin -I/<<PKGBUILDDIR>>/snapd-glib/.. -I/<<PKGBUILDDIR>>/obj-i686-linux-gnu/snapd-glib/.. -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/json-glib-1.0 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/<<PKGBUILDDIR>>/obj-i686-linux-gnu/snapd-glib --library snapd-glib-2 -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lsoup-3.0 -lgmodule-2.0 -ljson-glib-1.0 -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/sourcescanner.py", line 25, in <module>
    from .ccompiler import CCompiler
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/ccompiler.py", line 29, in <module>
    from distutils.msvccompiler import MSVCCompiler
ModuleNotFoundError: No module named 'distutils.msvccompiler'

**Comment by sergio-costas** [comment]
Mmm... distutils.msvccompiler...

In which system are you building it?

**Comment by sergio-costas** [comment]
Also, are you applying the patch against "1.65"? I tested with that, because 1.66 isn't out...

**Comment by sergio-costas** [comment]
Finally, do you have installed the distutils python3 module?

**Comment by rikmills** [comment]
@sergio-costas 

It is building on launchpad.net buildds against oracular, exactly as it would if uploaded to Ubuntu archive.

The patch is applied against 1.65, having fetched it afresh from the 1.65 which was previous uploaded and build.

python3-distiutils is not installed in the buildd at build time. However, when this previously successfuly built in the archive and just failed on armhf tests, python3-distiutils was not installed either. So that has not changed.

**Comment by sergio-costas** [comment]
The gobject-introspection scanner clearly requires the distutils module, that's why it's failing. Can you add it to the build dependencies, please?

**Comment by jbicha** [comment]
There is a [gobject-introspection bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1081284) in oracular-proposed triggered by the upload of setuptools 74. We are working on updating gobject-introspection. For this specific testing, you could also try building in a PPA without -proposed.

**Comment by rikmills** [comment]
> There is a [gobject-introspection bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1081284) in oracular-proposed triggered by the upload of setuptools 74. We are working on updating gobject-introspection. For this specific testing, you could also try building in a PPA without -proposed.

That makes sense. Will disable proposed in the PPA and retry builds. Thanks :)

**Comment by rikmills** [comment]
@sergio-costas got a successful build on armhf with the patches from your PR. Tests that previously failed pass.

https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3997/+build/28930059

Thank you! :)

**Comment by sergio-costas** [comment]
Good to know!!! Thanks for the report!
